### ISSUE TITLE
Question: photos from list

### ISSUE THREAD

**Issue by bonobo** [jekylltools/jekyll-ideal-image-slider#5]
Hi @jekylltools ,

I want to ask you if is possible to add photos to image slider, when I have names a URLs for each image stored in .yml data file and I want to use for loop to cycle through the list of photos.

It would look something like this:
`{% slider auto %}`
`  {% for photo in photos %}`
`      ![{{ photo.name }}]({{ photo.link }})`
`    {% endfor %}`
`{% endslider %}`

**Comment by jekylltools** [comment]
Yes, you can do this with https://github.com/jekylltools/jekyll-ideal-image-slider-include

**Comment by jekylltools** [comment]
Yes, you can do this with https://github.com/jekylltools/jekyll-ideal-image-slider-include

Create slider data for `example_slider` in `_data/sliders.yml`, then add slider to page
```
{% include slider.html selector="example_slider" %}
```

Will that work for you?

**Comment by jekylltools** [comment]
I misunderstood your question. Yes, you can access the names and URLs from the data file. Data is available in `site.data` 

Suppose we have data in `_data/photos.yml` then your example would look like this:

```
{% slider auto %}
{% for photo in site.data.photos %}
![{{ photo.name }}]({{ photo.link }})
{% endfor %}
{% endslider %}
``

More info here: http://jekyllrb.com/docs/datafiles

**Comment by jekylltools** [comment]
@bonobo I closed this issue, but let me know if you need more help with anything.
